# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wangtai/code/geekcode/iad

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wangtai/code/geekcode/iad

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wangtai/code/geekcode/iad/CMakeFiles /Users/wangtai/code/geekcode/iad//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wangtai/code/geekcode/iad/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iad

# Build rule for target.
iad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iad
.PHONY : iad

# fast build rule for target.
iad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/build
.PHONY : iad/fast

#=============================================================================
# Target rules for targets named iad_lib

# Build rule for target.
iad_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iad_lib
.PHONY : iad_lib

# fast build rule for target.
iad_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/build
.PHONY : iad_lib/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/helper.o: src/helper.cpp.o
.PHONY : src/helper.o

# target to build an object file
src/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/helper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/helper.cpp.o
.PHONY : src/helper.cpp.o

src/helper.i: src/helper.cpp.i
.PHONY : src/helper.i

# target to preprocess a source file
src/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/helper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/helper.cpp.i
.PHONY : src/helper.cpp.i

src/helper.s: src/helper.cpp.s
.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/helper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/helper.cpp.s
.PHONY : src/helper.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pipe_layout_generator.o: src/pipe_layout_generator.cpp.o
.PHONY : src/pipe_layout_generator.o

# target to build an object file
src/pipe_layout_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/pipe_layout_generator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/pipe_layout_generator.cpp.o
.PHONY : src/pipe_layout_generator.cpp.o

src/pipe_layout_generator.i: src/pipe_layout_generator.cpp.i
.PHONY : src/pipe_layout_generator.i

# target to preprocess a source file
src/pipe_layout_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/pipe_layout_generator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/pipe_layout_generator.cpp.i
.PHONY : src/pipe_layout_generator.cpp.i

src/pipe_layout_generator.s: src/pipe_layout_generator.cpp.s
.PHONY : src/pipe_layout_generator.s

# target to generate assembly for a file
src/pipe_layout_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/pipe_layout_generator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/pipe_layout_generator.cpp.s
.PHONY : src/pipe_layout_generator.cpp.s

src/tree2pipe.o: src/tree2pipe.cpp.o
.PHONY : src/tree2pipe.o

# target to build an object file
src/tree2pipe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/tree2pipe.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/tree2pipe.cpp.o
.PHONY : src/tree2pipe.cpp.o

src/tree2pipe.i: src/tree2pipe.cpp.i
.PHONY : src/tree2pipe.i

# target to preprocess a source file
src/tree2pipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/tree2pipe.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/tree2pipe.cpp.i
.PHONY : src/tree2pipe.cpp.i

src/tree2pipe.s: src/tree2pipe.cpp.s
.PHONY : src/tree2pipe.s

# target to generate assembly for a file
src/tree2pipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad.dir/build.make CMakeFiles/iad.dir/src/tree2pipe.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iad_lib.dir/build.make CMakeFiles/iad_lib.dir/src/tree2pipe.cpp.s
.PHONY : src/tree2pipe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... iad"
	@echo "... iad_lib"
	@echo "... tests"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pipe_layout_generator.o"
	@echo "... src/pipe_layout_generator.i"
	@echo "... src/pipe_layout_generator.s"
	@echo "... src/tree2pipe.o"
	@echo "... src/tree2pipe.i"
	@echo "... src/tree2pipe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

